Support use list
jakm/txmsgpackrpc pull request #5
Opened 2016-11-29 14:36 UTC by tobixx

Forwards to use_list param of msgpack.Unpacker

2016-12-11 14:07 UTC, jakm requested changes

2016-12-11 14:07 UTC, jakm commented on txmsgpackrpc/protocol.py
> +            packerEncoding=packerEncoding, unpackerEncoding=unpackerEncoding, useList=True)
suppose this should be useList=useList

2016-12-11 14:59 UTC, tobixx commented on txmsgpackrpc/protocol.py
> +            packerEncoding=packerEncoding, unpackerEncoding=unpackerEncoding, useList=True)
Sure, good catch. Updated.

2016-12-11 16:55 UTC, jakm commented
please rebase over actual master, I've moved tests because of some weird behaviour of trial in travis-ci

2016-12-12 09:27 UTC, tobixx commented
Rebase done.

2016-12-12 13:42 UTC, jakm approved these changes

2016-12-12 13:43 UTC, merged

2016-12-12 13:43 UTC, jakm commented
nice work, thanks